### ISSUE TITLE
Occasional Crashes of Unknown Origin

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/dwmblocks#10]
I haven't done any real bugtesting on this, but I've noticed that dwmblocks occasionally crashes without an obvious cause.

I'd like to figure out the origin of this, or perhaps have dwm babysit the process and continue to restart it if it isn't manually killed by the user.

Suggestions or ideas welcome.

**Comment by LukeSmithxyz** [comment]
Okay. I've figured it out. I was sending a `RTMIN` signal to it for a module I didn't have active, and in that case, it causes dwmblocks to exit.

Might want to put a failsafe in, otherwise it was sort of my own blunder.

**Comment by Si-Ki** [comment]
> Okay. I've figured it out. I was sending a `RTMIN` signal to it for a module I didn't have active, and in that case, it causes dwmblocks to exit.
> 
> Might want to put a failsafe in, otherwise it was sort of my own blunder.

I don't know what you just said because I'm a total newb to all this but I noticed that mine crashes when I do something to change the Memory usage drastically like closing my browser or opening it, if someone knows how to fix this please guide me.... 

Thanks :)
