### ISSUE TITLE
Statusbar freezes sometimes

### ISSUE THREAD

**Issue by isak102** [LukeSmithxyz/dwmblocks#102]
Recently my statusbar has started freezing randomly, I haven't been able to identify a pattern of when its happening. With freezing I mean that no blocks update and nothing works until I kill the program and then restart it.

**Comment by LukeSmithxyz** [comment]
When you kill dwmblocks, are you actually killing it or does it say something like "no process found." Sounds like dwmblocks might be dying somehow.

That can potentially be caused by sending a bogus refresh code to it in a script for a module that is not enabled.

**Comment by isak102** [comment]
> When you kill dwmblocks, are you actually killing it or does it say something like "no process found." Sounds like dwmblocks might be dying somehow.
> 
> That can potentially be caused by sending a bogus refresh code to it in a script for a module that is not enabled.

Yeah I am actually killing it, the process is still there

**Comment by LukeSmithxyz** [comment]
I can't say I've run into this issue. If you have made significant changes to the `config.h`, could you include it here?

**Comment by ethanv2** [comment]
I've ran into this problem too. The process just sits there idle at zero percent CPU usage indefinitely. Although it will run signal handlers (as clicking the bar still runs programs), it never updates the root window text. When it next happens, I'll hook up gdb and see if I can find what's causing it to hang.

**Comment by ethanv2** [comment]
Looking at the backtrace (http://ix.io/46ZE), it seems that this occurs when a signal handler takes some time to process and another is delivered while it is still connected to the display. As the top two signal handlers blocked on a call to ``pthread_mutex_lock``, it seems that the first handler locks a mutex on connection and doesn't unlock it in time for the other signal handlers to use, so they hang waiting for the mutext to unlock.

I think I know a solution. I'll open a PR when I finish it (https://www.gnu.org/software/libc/manual/html_node/Blocking-Signals.html).
