### ISSUE TITLE
Statusbar freezes

### ISSUE THREAD

**Issue by kmj9** [LukeSmithxyz/dwmblocks#106]
After last update statusbar freezes. When system is loaded it works fine but after some time freezes and clickable modules not responding also volume module not changing. I don't know what could cause this.

**Comment by 0xLaurens** [comment]
Merge #104 seems to cause me some trouble when calling the kill command. When changing the volume it freezes after a few proper updates for me.

**Comment by kmj9** [comment]
After last commit problem is solved for me.
