### ISSUE TITLE
ZSH segmentation fault

### ISSUE THREAD

**Issue by akim-13** [LukeSmithxyz/dwmblocks#107]
After adding too many blocks (>8-9) dwmblocks crashes because of the zsh error:

```
zsh: segmentation fault (core dumped)  dwmblocks
```

I found the same issue [here](https://github.com/torrinfail/dwmblocks/issues/9) and it seems like it got fixed and isn't present on Luke's (this) build. Not the case for me apparently. As mentioned there, it's related to the number of chars rather than the number of blocks, which is true (see my [config.h](https://github.com/akim-13/dwmblocks/blob/master/config.h)).

**Comment by se7en-x230** [comment]
I have the same problem but ONLY if the mpd notification script is running AND I guess the Artist/Album/Song info is very long.
At least this is what it looks like.
Any fix for that?
