### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by eriteric** [LukeSmithxyz/dwmblocks#109]
After a little while, all modules stop updating including the clock. I'll run `dwmblocks` and it will unfreeze for a while then go back to freezing again. 

- 5a6fa8d is the latest commit I have. 
- I have updated the clock script from the dotfiles repo
- arch

**Comment by eriteric** [comment]
https://github.com/LukeSmithxyz/dwmblocks/pull/104/commits - applied this fix, so far is working.

**Comment by eriteric** [comment]
No, it's still frozen. 
Is it possible for the signal numbers to get messed up? I am manually running kill -44 $(pidof dwmblocks) and nothing happens. Just restarted, checked and there is only one result from pidof dwmblocks.

**Comment by eriteric** [comment]
did a fresh clone and build and it works now, perhaps a bad merge at some point

**Comment by eriteric** [comment]
nope, still doing it.

**Comment by zargot** [comment]
I have the same issue.
- 66f31c3
- Artix (Linux 6.0.1-zen2-1-zen ZEN SMP PREEMPT_DYNAMIC Fri, 14 Oct 2022 20:48:02 +0000 x86_64 GNU/Linux)

**Comment by eriteric** [comment]
A script to run whenever it gets stuck (happens ~ once per hour).
```
#!/bin/bash
killall -q dwmblocks
setsid dwmblocks
```

**Comment by zargot** [comment]
> A script to run whenever it gets stuck (happens ~ once per hour).
> 
> ```
> #!/bin/bash
> killall -q dwmblocks
> setsid dwmblocks
> ```

Thank you. Mine doesn't freeze frequently, luckily. It's been going well ever since I posted. (My uptime is currently 9 days.) I didn't use `setsid` to start it again, just the normal dwm program launcher, dunno if that's relevant.

**Comment by eriteric** [comment]
Hm no, tried the script without `setsid`, didn't change anything.

**Comment by zargot** [comment]
Maybe it happens due to running a system update (with pacman), or some other system operation? Does it happen if you only do normal user operations, @eriteric? Maybe there's a cron job or something?

**Comment by eriteric** [comment]
yea, normal user operations. It happens way too quickly for cron jobs I think. The only cron jobs i have (aside from the one i made trying to fix this) are at most daily, and I only run updates manually, once a week or so. I do have snapper timers going hourly but even that is not quick enough to be the culprit. It can be 10-20 minutes until it freezes, and that is pretty consistent now. Basically every time I want to look at the clock I have to run the fix-it script. I'm going to do some more investigating in a couple days, on a work deadline atm. Thanks @zargot

**Comment by eriteric** [comment]
I have tried using the latest commit from torrinfall's dwmblocks, and that does the same thing. Also tried using gocaudices, that freezes too. lol. So, gonna close this. There's something else going on. I saw a segmentation fault with dwmblocks also, which there are several issues about. Don't know how to solve this yet but it's probably not specific to Luke's repo.

**Comment by eriteric** [comment]
well aint that how it normally goes....figured it out. After reading some of the closed segmentation fault issues I started eliminating blocks to get the character count down. I had only two and it was still freezing, volume and the clock. removed the clock and it no longer freezes. I had edited the sb-clock script to to be fairly long, listing the Ymd, an icon, time etc. So i guess it just had too many characters. Hopefully that issue is solved someday.

**Comment by zargot** [comment]
> I had edited the sb-clock script to to be fairly long, listing the Ymd, an icon, time etc. So i guess it just had too many characters.

Kudos @eriteric. How many is too many?

**Comment by eriteric** [comment]
@zargot thanks :) haha
This is what I had:
```
date "+%a %Y%m%d $icon%H:%M%p"
```
This is what I changed it to in order to get it working:
```
date "+%a %Y%m%d %H:%M"
```
Don't ask me why i was listing am/pm on military time before. Perhaps that was so dumb that the program refused to continue.

**Comment by zargot** [comment]
That is very interesting. I also removed am/pm shortly after having this issue, and I haven't had any problems after that.
I now have: `date "+%Y %b %d (%a) $icon%H:%M"`

**Comment by eriteric** [comment]
@zargot oh, weird. Tried some experiments:
Not sure if I waited long enough to check these thoroughly though.

## doesn't crash:
- `date "+%a %Y%m%d %H:%M"` (19 characters)
- `date "+%a %Y%m%d %H:%M%p"` (21 characters)
- `date "+%Y %b %d (%a) $icon%H:%M"` (24 characters)

## does crash:
- `date "+%a %Y%m%d $icon%H:%M%p"` (23 characters)

Strange that your 24 character one works and the 23 character one crashes.

If I try and make it even longer the clock just disappears from dwmblocks.

**Comment by eriteric** [comment]
Still working, and I have been enjoying this luxury of having a working clock very much. I shortened the output of some of the other modules as well. Not sure if it was accumulative among all the modules, or what.

**Comment by zargot** [comment]
I'm happy you finally got it working! :smile: Let me know if you figure out something more.
