### ISSUE TITLE
nothing shows up but on the original dwm it does

### ISSUE THREAD

**Issue by Toni500github** [LukeSmithxyz/dwmblocks#112]
so i have installed Luke dwm, copied the voidrice binaries and exported the folders on my  `$PATH`. but when i launch luke dwm, nothing shows up meanwhile on the original dwm it does

**Comment by FuriousGamer1356** [comment]
I am having the same problem as you. Have you found a solution yet?

**Comment by LukeSmithxyz** [comment]
https://github.com/LukeSmithxyz/LARBS/issues/522
