### ISSUE TITLE
Bar doesn't show up on startup

### ISSUE THREAD

**Issue by mtarunsai1999** [LukeSmithxyz/dwmblocks#15]
I have tried putting dwmblocks & command in .xprofile and dwm autostart, but didn't work. It has a pid assigned to it though. It works after I type dwmblocks & in terminal. What should I do?

**Comment by LukeSmithxyz** [comment]
Depends on your setup. If, for example, you're using the independent scripts like this build has, you will want to make sure your `PATH` variable has been updated _before_ dwmblocks is run. That could be the issue.

**Comment by mtarunsai1999** [comment]
Thank you for the direction. Changed `PATH` declaration to .profile, now it works.
