### ISSUE TITLE
dwmblocks crashes

### ISSUE THREAD

**Issue by NicholasasaurusRex** [LukeSmithxyz/dwmblocks#16]
This maybe the same issue, [Crashes when receiving unassigned signal number #10](https://github.com/LukeSmithxyz/dwmblocks/issues/10) But you never said what unused module was causing the issue. I couldn't find the fix in any commit you did either. What was your fix? so I might be able to see if I have the same problem?

I have looked at all the modules that update and silenced any that have a RTMIN, still get the crash.

Took a hacky solution to try and solve it by having a crontab run refdwmblocks script ever 5 minutes to see if that worked (because running refdwmblocks works in the terminal so why shouldn't it work with a cronie?) but that will actually case it to crash also when the cron job runs.

What did you do to stop dwmblocks from randomly crashing, and crashing upon using the update modules in ``` ~/.local/bin/cron/*```

This maybe the same issue as: [Crashes when receiving unassigned signal number #10](https://github.com/LukeSmithxyz/dwmblocks/issues/10) but I cannot figure out what module if any is causing dwmblocks to crash on my end.

**Comment by LukeSmithxyz** [comment]
In my case, I had added a module that I had updated by a cronjob signaling to it every once in a while. When I removed the module, the cronjob would still run and still signal to dwmblocks, but since the module had been deactivated, dwmblocks would crash. All I had to do is turn off that (useless anyway) cronjob.

I can't attest to your case. Just think if you added a cronjob, or script that signals to dwmblocks that you later removed or changed its number.

**Comment by LukeSmithxyz** [comment]
Actually, I'll say the only way I realized what I had done and how it had been caused is by manually editing dwm (or whatever is running dwmblocks) and have it output error to a log file `2>> ~/log`.

Then I easily saw that when it received an unknown signal, it interpreted that as a typical `TERM` signal.

**Comment by NicholasasaurusRex** [comment]
So I have managed to crash dwmblocks reliably in several ways. And can reproduce them. 1. Most easily reproducible for me is close the lid to my laptop and reopen (very low concern as super+d refdwmblocks take literally 2 seconds, but worth mentioning as a cronjob type solution could fix this.) 2. Run any cronjob that refreshes any module in dwmblocks.

I am going to clunk away at this for a couple days if you don't mind leaving this issue open and if/when I manage hopefully to find a fix I can patch it. OR another solution if I can find a way to reliably refresh dwmblocks with a cronjob (preferably because not everyone uses systemd) or secondarily a systemd.timer that can suffice for anyone else who may run into this and just want a bandaid temporarily I suppose.

**Comment by NicholasasaurusRex** [comment]
I am going to start running a log like you did to see what is there ```bash 2>> ~/log``` oddly enough that the ```bash ~/.local/bin/statusbar/popupgrade``` script, even if not ran or used. If not deleted or commented out completely, maybe? causing dwmblocks to crash? ever since I got rid of that script when for 2+ days. dwmblocks has not crashed at all.

**Comment by LukeSmithxyz** [comment]
What is the way that you are running cronjobs? They have been zero problem for me so long as they are signaling the correct numbers. I tried them directly as cronjobs and inside scripts.

Now you could have dwmblocks started in a loop in dwm. That is, have it start dwmblocks and if it crashes, wait a second and restart it.

**Comment by LukeSmithxyz** [comment]
> I am going to start running a log like you did to see what is there `2>> ~/log` oddly enough that the ` ~/.local/bin/statusbar/popupgrade` script, even if not ran or used. If not deleted or commented out completely, maybe? causing dwmblocks to crash? ever since I got rid of that script when for 2+ days. dwmblocks has not crashed at all. This maybe coincidental.

Well `popupgrade` signals 8 to dwmblocks. If you do not have the `pacpackages` module activated (or have changed it to a number other than 8), this 100% is causing your crash.

**Comment by NicholasasaurusRex** [comment]
BOOM! there it is for the popupgrade issue.
and BOOMER! the loop works having dwmblocks started in a loop on dwm!

So this actually works for me not (check out the big brain on luke over here...)

I and going to play with my cronjob to see why I am still having dwmblocks crash with certain scripts. But I don't think that has anything to do with dwmblocks. So I would easily say this issue is closed. Thanks Luke.
