### ISSUE TITLE
weather, battery, and volume not appearing in the status bar.

### ISSUE THREAD

**Issue by sudo-ghost** [LukeSmithxyz/dwmblocks#17]
weather just shows **spawn telnet rainmaker.wunderground.com 3000**

im guessing the part showing **unknown 95** next to it is my bat percentage.

volume  just doesnt show up at all 

the only things being displayed are the time and date and the network %.

**Comment by LukeSmithxyz** [comment]
For the volume, what output does the command `pactl list sinks` yield?

Are you using some weird distro or maybe a BSD? `unknown 95` is probably your battery, but it should be outputting `Unknown` with a capital u, which would be converted to the corresponding icon.

Not sure what's going on with the weather module. Might want to delete ~/.local/share/weatherreport and reload and see what happens.

**Comment by sudo-ghost** [comment]
pactl list sink yeilds `Sink #0
	State: SUSPENDED
	Name: alsa_output.pci-0000_00_1f.3.analog-stereo
	Description: Built-in Audio Analog Stereo
	Driver: module-alsa-card.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 6
	Mute: no
	Volume: front-left: 30419 /  46% / -20.00 dB,   front-right: 30419 /  46% / -20.00 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "CX20753/4 Analog"
		alsa.id = "CX20753/4 Analog"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xf1320000 irq 134"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1f.3"
		sysfs.path = "/devices/pci0000:00/0000:00:1f.3/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "9d71"
		device.product.name = "Sunrise Point-LP HD Audio"
		device.form_factor = "internal"
		device.string = "front:0"
		device.buffering.buffer_size = "352800"
		device.buffering.fragment_size = "176400"
		device.access_mode = "mmap+timer"
		device.profile.name = "analog-stereo"
		device.profile.description = "Analog Stereo"
		device.description = "Built-in Audio Analog Stereo"
		alsa.mixer_name = "Conexant CX20753/4"
		alsa.components = "HDA:14f15111,17aa5068,00100101 HDA:8086280b,80860101,00100000"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Ports:
		analog-output-speaker: Speakers (priority: 10000)
		analog-output-headphones: Headphones (priority: 9900, not available)
	Active Port: analog-output-speaker
	Formats:
		pcm`


as for the distro im using **Arch**

and deleting **weatherreport** did not change anything.

**Comment by LukeSmithxyz** [comment]
Could you give me that output properly formatted as it appears? That is highly relevant. Or does it appear like that, lol?

What is your system's `$LANG` variable? Any weird language settings? Anything unique you've configured your system with?

I've patched the battery script. It should be able to handle systems like yours, but I just don't know what is wrong with your system right now...

**Comment by sudo-ghost** [comment]
My bad, this is how it was formatted 

Sink #0
	State: SUSPENDED
	Name: alsa_output.pci-0000_00_1f.3.analog-stereo
	Description: Built-in Audio Analog Stereo
	Driver: module-alsa-card.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 6
	Mute: no
	Volume: front-left: 30419 /  46% / -20.00 dB,   front-right: 30419 /  46% / -20.00 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "CX20753/4 Analog"
		alsa.id = "CX20753/4 Analog"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xf1320000 irq 134"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1f.3"
		sysfs.path = "/devices/pci0000:00/0000:00:1f.3/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "9d71"
		device.product.name = "Sunrise Point-LP HD Audio"
		device.form_factor = "internal"
		device.string = "front:0"
		device.buffering.buffer_size = "352800"
		device.buffering.fragment_size = "176400"
		device.access_mode = "mmap+timer"
		device.profile.name = "analog-stereo"
		device.profile.description = "Analog Stereo"
		device.description = "Built-in Audio Analog Stereo"
		alsa.mixer_name = "Conexant CX20753/4"
		alsa.components = "HDA:14f15111,17aa5068,00100101 HDA:8086280b,80860101,00100000"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Ports:
		analog-output-speaker: Speakers (priority: 10000)
		analog-output-headphones: Headphones (priority: 9900, not available)
	Active Port: analog-output-speaker
	Formats:
		pcm



as for $LANG the output is **en_US.UTF-8**

as for system configuration its mostly the default LARBS setup but ive edited things like **zshrc** **vimrc** **.profile** etc.

**Comment by LukeSmithxyz** [comment]
Weird. With that output, the volume module is working for me. Maybe I'm missing something.

On weather, if you run `curl -sf "wttr.in/$LOCATION"` manually, do you get a weather report or does some error appear?

Now what if you run `curl -sf "wttr.in/$LOCATION" > "${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"`? Does the weather module fix itself on update/click?

**Comment by sudo-ghost** [comment]
running `curl -sf "wttr.in/$LOCATION"` does give me it manually but running   **curl -sf "wttr.in/$LOCATION" > "${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"** does not fix the module. could it be something on my end with telnet? i was looking through the issues and i couldn't find anything similar to what im experiencing. i gotta go do some stuff so ill check back latter.

**Comment by LukeSmithxyz** [comment]
Now is there anything different if you run `volume` or `weather` manually in the command line?

Maybe you're having a ping error on the weather script...

**Comment by sudo-ghost** [comment]
running `volume`  from the command line gets me `ALSA lib control.c:1379:(snd_ctl_open_noupdate) Invalid CTL hw:`

and running weather from the command line gets me the automated script but it will end with `connection closed by foreign host`. would you like the entire output of the weather command after its run in the command line?

**Comment by RokasR3D** [comment]
Also had the same telnet message. Turns out dwblocks was running a program called "weather" from a package "expect".
`which weather
/usr/bin/weather
`
Removed the package and made sure the command "weather" runs:
`curl wttr.in/$LOCATION?format=3`

Works on fedora 31

**Comment by LukeSmithxyz** [comment]
> Also had the same telnet message. Turns out dwblocks was running a program called "weather" from a package "expect".
> `which weather /usr/bin/weather `
> Removed the package and made sure the command "weather" runs:
> `curl wttr.in/$LOCATION?format=3`
> 
> Works on fedora 31

Lol of course this is an issue that obvious... Man, okay, I guess I'll rename the script for good measure. Frankly, most of the scripts in the statusbar have pretty generic names that might be doubled up.

**Comment by LukeSmithxyz** [comment]
I fixed this a while ago by renaming the scripts. Closing now.
