### ISSUE TITLE
Internet module fix for desktop PC

### ISSUE THREAD

**Issue by AlexSyssoyev** [LukeSmithxyz/dwmblocks#19]
Hello, i use a Desktop PC without wifi card. So the internet module crashes when loaded into dwmblocks (complaining about /sys/class/net/w*/operstate not existing), when i started using it i commented out this lines: 

```
grep -q "down" /sys/class/net/w*/operstate && wifiicon="📡" ||
	wifiicon="$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')"
```

Today out of boredom i decided to take on it and try to fix it, but i feel that my patch is sloppy and there should be a better way to do it, so i will leave it here and learn from someone a better solution.

I added this line so it would check if the file exists, but since i don't have wifi on my pc i can't check if it works as solution.
```
[ $(grep "^\s*w" /proc/net/wireless) ] &&
	grep -q "down" /sys/class/net/w*/operstate && wifiicon="📡" ||
	wifiicon="$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')"
```

Thanks for the patience.

**Comment by LukeSmithxyz** [comment]
Oh okay. So when you say it crashes, do you mean the module doesn't appear or dwmblocks doesn't appear at all?

**Comment by LukeSmithxyz** [comment]
I've changed this in the dotfiles. I used a case statement to minimize calls of files. Say so if it doesn't work!

**Comment by AlexSyssoyev** [comment]
Yes exactly, thanks!, works perfectly now.
