### ISSUE TITLE
Plan for adding systemtray?

### ISSUE THREAD

**Issue by jcguu95** [LukeSmithxyz/dwmblocks#21]
I found systemtray helpful most of the time. There's a [patch](https://dwm.suckless.org/patches/systray/) for it but does not patch immediately (need some work). Wonder if there's a plan to add it in.

**Comment by LukeSmithxyz** [comment]
No. See all the other issues on this I closed in the dwm repository.

**Comment by jcguu95** [comment]
Sure, thanks for clarifying! For those who are also wondering, here are the links to those discussions:

+ https://github.com/LukeSmithxyz/dwm/pull/35
+ https://github.com/LukeSmithxyz/dwm/issues/37
+ https://github.com/LukeSmithxyz/dwm/pull/50
