### ISSUE TITLE
notify send error when clicking dwmblocks modules

### ISSUE THREAD

**Issue by Abh15h3k** [LukeSmithxyz/dwmblocks#24]
I'm trying Artix with openrc. 
setup using larbs
But when I left click the cpu or memory part of dwmblocks it doesn't show the notification popup with the 10 processes.

Also this error shows up in my ~/.xsession-errors

```
(notify-send:2977): GLib-WARNING **: 14:04:35.909: In call to g_spawn_sync(), exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.
```

**Comment by Abh15h3k** [comment]
So tried some stuff and this is my situation.

dwmblocks is not showing any popup for clicks when the respective script has `#!/bin/sh` shebang.
If i change it to `#!/bin/zsh` it shows the popup.

This link contains a screen capture illustrating this issue. hope it helps. ( the link expires after 24 hours. ill try to keep it updated till a conclusion is reached ).

https://a.uguu.se/pGc37bFgt0Vr_dwmblocks.mp4

**Comment by et-8** [comment]
I'm getting the same error on Gentoo with OpenRC.

**Comment by Abh15h3k** [comment]
For some reason when dwmblocks executes the script notify-send does not work.
right now the only workaround i have is making another script with the following

```
#!/bin/sh
notify-send $@
```

and calling this script instead of notify-send and it works for me.

**Comment by LukeSmithxyz** [comment]
To be clear, while your title talks about cpu and memory, do the other modules' help menus work when right clicked?

**Comment by Abh15h3k** [comment]
No. Notify-send does not work with any modules.

**Comment by Abh15h3k** [comment]
Here's the latest screencap of this issue.
https://a.uguu.se/fYcjWqKRdy3T_dwmblocks-notify-send.mp4

calling the script from terminal works as expected but not when clicking dwmblocks.
only if i set the shebang to `#!/bin/zsh` or use another script to call notify-send which needs to have `#!/bin/zsh`.

one thing i realised is that when i type `sh` in artix. i get `sh-5.0$` shell prompt instead of the usual bash prompt which i get when i type `bash`.

but when i type `sh --version` and `bash --version` the outputs are identical.
Both say `GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)`

**Comment by Abh15h3k** [comment]
I just glanced through `dwmblocks.c` to find out how the scripts are called by dwmblocks. i got this command `/bin/sh -c export BLOCK_BUTTON=1;clock` and this when executed in terminal does not work. it just shows me all the exports and the output of the clock script in the terminal.

**Comment by Abh15h3k** [comment]
To clarify one thing. This issue is not only when trying to click the blocks. notify-send does not working even when it is simply in the script.

I cloned torrinfail's dwmblocks and his build executed notify-send in scripts correctly.

So i compared the source codes and after a bit of commenting out code in your build. i was left with only this line being the difference between your source and torrinfail's `signal(SIGCHLD, SIG_IGN);`. which i know is there to prevent zombie processes. But removing/commenting out that line results in notify-send executing correctly. But on the other hand now there will be zombie processes.

**Comment by Abh15h3k** [comment]
did some more digging and i found an alternative to `signal(SIGCHLD, SIG_IGN);` from this stackoverflow question https://stackoverflow.com/questions/17015830/how-can-i-prevent-zombie-child-processes.

basically instead of doing  `signal(SIGCHLD, SIG_IGN);` you do this:

```
        struct sigaction sigchld_action = {
            .sa_handler = SIG_DFL,
            .sa_flags = SA_NOCLDWAIT
        };
        sigaction(SIGCHLD, &sigchld_action, NULL);
```

doing the above results in no zombie processes and notify-send executes correctly as well.

**Comment by LukeSmithxyz** [comment]
Okay. I don't know too much about what the difference here should be yet, but I might merge that change if it works without disastrous outcomes.

**Comment by Abh15h3k** [comment]
In many places people are saying that using the structure method is just the POSIX way of doing `signal(SIGCHLD, SIG_IGN);` so there should be no difference that would cause any catastrophic issue.

But please look into it and IF there is some evidence of problem/issues avoid it. In my few hours of digging i have not found any.

**Comment by et-8** [comment]
Both the shebang `#!/bin/zsh` method and the `structure` method worked for me. I'll also use the `structure` method and keep a lookout for any errors or disruption.

**Comment by Abh15h3k** [comment]
So. been using this for more than a day on both artix (openrc) and archlinux (systemd) nothing went wrong. no errors or odd behaviour. I'll close this issue for now.
