### ISSUE TITLE
Small Squares Next To Icons

### ISSUE THREAD

**Issue by Caleb68864** [LukeSmithxyz/dwmblocks#26]
I installed dwmblocks and believe I have all the scripts in the right places and made sure my scrips are loading in zprofile.
However, there are small squares to the left of each icon on the bar.
The icons still print.
It not the delimiter as I was able to change that and it worked without issue.

Is there a package I am missing?

Thanks,

**Comment by Shadorain** [comment]
I am having the same error as well, ive read through the source more times than i wanted, and have made so many git branches to try and fix it that i dont even wanna mention the number. It's quite an obnoxious issue and nothing i do or try seems to work. Thanks

**Comment by Shadorain** [comment]
Welp all that damn time, all for a simple patch, its some sort of signal issue mah dude. Try adding the dwm-statuscmdsignal patch: https://dwm.suckless.org/patches/statuscmd/dwm-statuscmd-signal-6.2.diff 
This fixed it for me, i wish Luke said the exact patch to get tho either on the vid or his README. I have been trying for like all day :sweat: . 
Hope this helps :grin: @Caleb68864

**Comment by Caleb68864** [comment]
Adding the patch didn't help but I am still working on getting the click signals to work properly. So I imagine once I get those working it will solve the issue.

**Comment by nguyenhaiac** [comment]
> Welp all that damn time, all for a simple patch, its some sort of signal issue mah dude. Try adding the dwm-statuscmdsignal patch: https://dwm.suckless.org/patches/statuscmd/dwm-statuscmd-signal-6.2.diff
> This fixed it for me, i wish Luke said the exact patch to get tho either on the vid or his README. I have been trying for like all day sweat .
> Hope this helps grin @Caleb68864

The solution works for me, thank you.

**Comment by Mikeltxo15** [comment]
> Welp all that damn time, all for a simple patch, its some sort of signal issue mah dude. Try adding the dwm-statuscmdsignal patch: https://dwm.suckless.org/patches/statuscmd/dwm-statuscmd-signal-6.2.diff
> This fixed it for me, i wish Luke said the exact patch to get tho either on the vid or his README. I have been trying for like all day  .
> Hope this helps  @Caleb68864

This solution worked for me as well! Although 1 of the hunks failed to apply when I patched dwm, and I had to get into the code and apply it manually.
If anyone wants to know, I only had to apply the patch to dwm for this problem to be solved, I didn't modify anything with dwmblocks code. I don't think this is intended behaviour, the patch page in the suckless page specifies the patch is used for the BLOCK feature. And for those who don't want this feature, like me, dwmblocks should work straight out of the box.
OH! Another thing, unrelated to this package. If anyone is having problems recently with emoji rendering, even after installing libxft-bgra package and removing the iscol segment in dwm and dmenu's code, the recent fontconfig update broke it for me. Downgrading that package alone fixed it.

**Comment by Shadorain** [comment]
> > Welp all that damn time, all for a simple patch, its some sort of signal issue mah dude. Try adding the dwm-statuscmdsignal patch: https://dwm.suckless.org/patches/statuscmd/dwm-statuscmd-signal-6.2.diff
> > This fixed it for me, i wish Luke said the exact patch to get tho either on the vid or his README. I have been trying for like all day  .
> > Hope this helps  @Caleb68864
> 
> This solution worked for me as well! Although 1 of the hunks failed to apply when I patched dwm, and I had to get into the code and apply it manually.
> If anyone wants to know, I only had to apply the patch to dwm for this problem to be solved, I didn't modify anything with dwmblocks code. I don't think this is intended behaviour, the patch page in the suckless page specifies the patch is used for the BLOCK feature. And for those who don't want this feature, like me, dwmblocks should work straight out of the box.
> OH! Another thing, unrelated to this package. If anyone is having problems recently with emoji rendering, even after installing libxft-bgra package and removing the iscol segment in dwm and dmenu's code, the recent fontconfig update broke it for me. Downgrading that package alone fixed it.

patching manually is actually quite a joyous thing to do, you also see the code of your own window manager too so u get some experience with it as well.
abuot the whole issue after, not sure why its like that, i 100% made it all my own and took out everything that was pre configured so i didnt have any of those issues
