### ISSUE TITLE
Whst does the `update signal` value actually mean?

### ISSUE THREAD

**Issue by sleeperzjf** [LukeSmithxyz/dwmblocks#27]
Sorry if I asked a stupid question but I'm really confused.

**Comment by Abh15h3k** [comment]
update signal is used to manually update a particular block on the status bar.
a good example would be the volume block ( whose signal is 10 ). by default the volume block does not update regularly.

so lets say you use a keybind to change the volume. that change would not reflect on the status bar.
so what you do is send a signal to dwmblocks to tell it to update the volume block.
this is how you would do it. 
`pamixer -i 10; pkill -RTMIN+10 dwmblocks`

to update any other block replace 10 with its corresponding signal from config.h

**Comment by sleeperzjf** [comment]
@Abh15h3k Thanks a lot! Now I understand.
