### ISSUE TITLE
cpu, memory, internet and weather does not appear and keeps bugging dwmblocks.

### ISSUE THREAD

**Issue by apoorv569** [LukeSmithxyz/dwmblocks#30]
whenever i try to open the cpu memory, internet and weather scripts in vim or nano its crashes/closes the terminal window, only way i can edit them if i use a graphical text editor, also they don't show on status bar. i tried to run the script in terminal `./(script-name)`, terminal crashes and closes. clicking on the modules does nothing it shows a notification saying Mouse 1, Mouse 3

also the emoji's show as black and white rather than colored emoji's,

and im not able to adjust volume and brightness when in dwm, as im on a laptop and i don't know how to bind the volume and brightness and airplane mode and all those keys to appropriate keys which are on Fn keys.

btw im using vanilla dwmblocks, just grabbed your scripts for modules.

**Comment by Abh15h3k** [comment]
what dwm are you using?
if vanilla dwm. then color emojis are "disabled" by default.
in `drw.c` at around `line 142` you have to remove the following

```
	FcBool iscol;
	if(FcPatternGetBool(xfont->pattern, FC_COLOR, 0, &iscol) == FcResultMatch && iscol) {
		XftFontClose(drw->dpy, xfont);
		return NULL;
	}
```

**Comment by apoorv569** [comment]
> Edit: This is for emojis showing as black and white.
> 
> what dwm are you using?
> if vanilla dwm. then color emojis are "disabled" by default.
> in `drw.c` at around `line 142` you have to remove the following
> 
> ```
> 	FcBool iscol;
> 	if(FcPatternGetBool(xfont->pattern, FC_COLOR, 0, &iscol) == FcResultMatch && iscol) {
> 		XftFontClose(drw->dpy, xfont);
> 		return NULL;
> 	}
> ```

thanx its working now. can you help me with other problem i have?

**Comment by Abh15h3k** [comment]
what linux and terminal are you using?

**Comment by apoorv569** [comment]
> EDIT: terminal crashing while editing the scripts.
> what linux and terminal are you using?
> 
> For brightness and volume control add these keybinds in your config.def.h (of dwm)
> change the arguments for the SHCMD's with what you use.
> 
> ```
> 	{ 0, XF86XK_AudioMute,		spawn,		SHCMD("volctl mute") },
> 	{ 0, XF86XK_AudioRaiseVolume,	spawn,		SHCMD("volctl inc 5") },
> 	{ 0, XF86XK_AudioLowerVolume,	spawn,		SHCMD("volctl dec 5") },
> 	{ 0, XF86XK_MonBrightnessUp,	spawn,		SHCMD("light -A 5") },
> 	{ 0, XF86XK_MonBrightnessDown,	spawn,		SHCMD("light -U 5") },
> ```

im using Arch Linux, terminal is st, i have the those keybidings you told working now but the display which sets the display to be extended mirrored and all and airplane mode key are not working still. and also when raising birghtness or volume the modules in status bar are not updating. do i have to define somwhere which signal does what?

**Comment by Abh15h3k** [comment]
install `libxft-bgra` from aur for st crashing.

check LukeSmithxyz's dwm config. it has many of the laptop keybinds. use what you need.

for dwmblocks to update.  make it such that right after your command u do `pkill -RTMIN+x dwmblocks`. 
x is your update signal value in blocks.h for the particular block.

**Comment by Abh15h3k** [comment]
for spotify install `playerctl` and run it once in terminal to see how to control players. then in dwm bind the keys as need. for example.
`{ 0, XF86XK_AudioPlay,		spawn,		SHCMD("playerctl -a play") }`

it works with vlc probably because it grabs those keys itself. spotify does not do that. so you need `playerctl`

**Comment by apoorv569** [comment]
> pkill -RTMIN+x dwmblocks

where do i have to put this line in blocks.h?

**Comment by Abh15h3k** [comment]
> > pkill -RTMIN+x dwmblocks
> 
> where do i have to put this line in blocks.h?

not in blocks.h. in dwm's config.def.h
lets say you use pamixer to change volume your keybind will be
`{ 0, XF86XK_AudioRaiseVolume,	spawn,		SHCMD("pamixer -i 5 && pkill -RTMIN+10 dwmblocks") }`
you have to do this only if u set the update interval to 0. and for all keybinds.

**Comment by apoorv569** [comment]
> > > pkill -RTMIN+x dwmblocks
> > 
> > 
> > where do i have to put this line in blocks.h?
> 
> not in blocks.h. in dwm's config.def.h
> lets say you use pamixer to change volume your keybind will be
> `{ 0, XF86XK_AudioRaiseVolume, spawn, SHCMD("pamixer -i 5 && pkill -RTMIN+10 dwmblocks") }`
> you have to do this only if u set the update interval to 0. and for all keybinds.

and for brightness also i give it the appropriate singal number and pkill command?

**Comment by Abh15h3k** [comment]
> > > > pkill -RTMIN+x dwmblocks
> > > 
> > > 
> > > where do i have to put this line in blocks.h?
> > 
> > 
> > not in blocks.h. in dwm's config.def.h
> > lets say you use pamixer to change volume your keybind will be
> > `{ 0, XF86XK_AudioRaiseVolume, spawn, SHCMD("pamixer -i 5 && pkill -RTMIN+10 dwmblocks") }`
> > you have to do this only if u set the update interval to 0. and for all keybinds.
> 
> and for brightness also i give it the appropriate singal number and pkill command?

yup.
basically for any block that have update interval set to 0 in blocks.h
you have to use the pkill command to update. interval of 0 means that the block script will only run once when dwmblocks starts.

**Comment by apoorv569** [comment]
> > > > > pkill -RTMIN+x dwmblocks
> > > > 
> > > > 
> > > > where do i have to put this line in blocks.h?
> > > 
> > > 
> > > not in blocks.h. in dwm's config.def.h
> > > lets say you use pamixer to change volume your keybind will be
> > > `{ 0, XF86XK_AudioRaiseVolume, spawn, SHCMD("pamixer -i 5 && pkill -RTMIN+10 dwmblocks") }`
> > > you have to do this only if u set the update interval to 0. and for all keybinds.
> > 
> > 
> > and for brightness also i give it the appropriate singal number and pkill command?
> 
> yup.
> basically for any block that has update interval set to 0 in blocks.h
> you have to use the pkill command to update. interval of 0 means that the block script will only run once when dwmblocks starts.

yup its all working now thanks alot bro :D
there are some scripts that i grabbed from luke that not working mainly internet weather cpu and pacupdate

**Comment by Abh15h3k** [comment]
> though i dont understand battery module updates fine when i remove the charging and all.
The update interval for you battery script is probably greater than 0. meaning dwmblocks will periodically re-run that script to keep it updated.

> there are some scripts that i grabbed from luke that not working mainly internet weather cpu
what exactly is not working in these scripts?

> pacupdate
for this one to work properly you need to have `pacman -Sy` to run (as root)  just before pacupdate runs so that the repositories are updated. its all mentioned in the script itself

**Comment by Abh15h3k** [comment]
> also click on them does nothing it just shows a notification saying MOUSE 1 or MOUSE 2

For clickable part of dwmblocks you need a patch for dwm itself. 
https://dwm.suckless.org/patches/statuscmd/
the way it works is dwm grabs the click and sends the signal to dwmblocks with a environment variable set for which mouse button is pressed.

**Comment by apoorv569** [comment]
> > also click on them does nothing it just shows a notification saying MOUSE 1 or MOUSE 2
> 
> For clickable part of dwmblocks you need a patch for dwm itself.
> https://dwm.suckless.org/patches/statuscmd/
> the way it works is dwm grabs the click and sends the signal to dwmblocks with a environment variable set for which mouse button is pressed.

i have that patch already included in my build the statuscmd.

**Comment by Abh15h3k** [comment]
> i have that patch already included in my build the statuscmd.

try changing `case $BLOCK_BUTTON in` to `case $BUTTON in` in the scripts.

**Comment by apoorv569** [comment]
> > i have that patch already included in my build the statuscmd.
> 
> try changing `case $BLOCK_BUTTON in` to `case $BUTTON in` in the scripts.

still nothing it just a notification saying MOUSE 1  MOUSE 2 MOUSE 3

if you want i can send my config for dwmblocks and dwm itself.

**Comment by Abh15h3k** [comment]
> if you want i can send my config for dwmblocks and dwm itself.
also one of the scripts that isn't working.
use pastebin.com to share them. don't just copy paste them here

**Comment by apoorv569** [comment]
> > if you want i can send my config for dwmblocks and dwm itself.
> 
> also one of the scripts that isn't working.
> use pastebin.com to share them. don't just copy paste them here

well the scripts im using are the exact as provided here - https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin/statusbar
and here is my dwm config.h - https://pastebin.com/EE1xxXen
and dwmblocks blocks.h - https://pastebin.com/ZCSgV2JK

im using vanilla everything i patched everything my self just grabbed the scripts from luke's repo. and few lines from luke's block.h file for corresponding scripts.

**Comment by Abh15h3k** [comment]
```
    { ClkStatusText,        0,              Button1,        spawn,          {.v = statuscmd } },
    { ClkStatusText,        0,              Button2,        spawn,          {.v = statuscmd } },
    { ClkStatusText,        0,              Button3,        spawn,          {.v = statuscmd } },
```

remove these three lines. rebuild logout and login and try

**Comment by apoorv569** [comment]
> in dwm's config.h
> 
> ```
>     { ClkStatusText,        0,              Button1,        spawn,          {.v = statuscmd } },
>     { ClkStatusText,        0,              Button2,        spawn,          {.v = statuscmd } },
>     { ClkStatusText,        0,              Button3,        spawn,          {.v = statuscmd } },
> ```
> 
> remove these three lines. rebuild logout and login and try
> EDIT: also in dwmblocks blocks.h best to keep unique signals numbers for every block.( your memory and cpu entries have the same signal.)

still clicking does nothing but im not getting any notification now either.

**Comment by Abh15h3k** [comment]
pastebin your dwmblocks.c

**Comment by apoorv569** [comment]
> pastebin dwmblocks.c
> 
> `pkill dwmblocks`.
> then run dwmblocks from a terminal and try clicking. do u get any output in the terminal?

```
> pkill dwmblocks
> dwmblocks                                                                                                                                                                      
cat: /home/apoorv/.pacupdate: No such file or directory
```

when i click on the status bar it killed the command and gave this output

`[1]    695845 user-defined signal 1  dwmblocks`

dwmblocks.c - https://pastebin.com/U4FvVYqt

**Comment by Abh15h3k** [comment]
> when i click on the status bar it killed the command and gave this output
> [1] 695845 user-defined signal 1 dwmblocks

when u applied the patch to dwmblocks. did you get anything like "1 out of 4 chunks failed"?

**Comment by apoorv569** [comment]
> > when i click on the status bar it killed the command and gave this output
> > [1] 695845 user-defined signal 1 dwmblocks
> 
> when u applied the patch to dwmblocks. did you get anything like "1 out of 4 chunks failed"?

no its patched successfully as far as i remember, even if it did i must have manually patched it added the lines

**Comment by Abh15h3k** [comment]
i just compiled your dwmblocks.c and blocks.h and its working for me.
could you try this script once. add it to your blocks.h (full path). make sure its executable
`	{"", "~/cpu",	1,		0},`

https://pastebin.com/faPMChjY

**Comment by apoorv569** [comment]
> i just compiled your dwmblocks.c and blocks.h and its working for me.
> could you try this script once. add it to your blocks.h (full path). make sure its executable
> ` {"", "~/cpu", 1, 0},`
> 
> https://pastebin.com/faPMChjY

its showing the cpu temp in status bar but clicking does nothing still :(

**Comment by Abh15h3k** [comment]
```
dwm-statuscmd-6.2.diff
dwm-statuscmd-signal-6.2.diff
dwmblocks-statuscmd.diff
```

which patches for the above did u apply?

**Comment by apoorv569** [comment]
> ```
> dwm-statuscmd-6.2.diff
> dwm-statuscmd-signal-6.2.diff
> dwmblocks-statuscmd.diff
> ```
> 
> which patches for the above did u apply?

all 3.
i also noticed right now my statusbar is just showing memory brightness temp volume battery and clock the other modules keep appearing and disappearing internet weather

**Comment by Abh15h3k** [comment]
> all 3.

from what i understand dwm-statuscmd and dwm-statuscmd-signal are mutually exclusive.
could you apply only the last 2 patches and try.

**Comment by apoorv569** [comment]
> > all 3.
> 
> from what i understand dwm-statuscmd and dwm-statuscmd-signal are mutually exclusive.
> could you apply only the last 2 patches and try.

well for that i have re do everything from start i dont have a build without the statuscmd patch. is there a way to delete a patch unpatch?

**Comment by Abh15h3k** [comment]
i would recommend re do everything. those 2 patches have alot of common code.

**Comment by apoorv569** [comment]
> i would recommend re do everything. those 2 patches have alot of common code.

hmm ok, i will get back to you when its done

**Comment by apoorv569** [comment]
> > i would recommend re do everything. those 2 patches have alot of common code.
> 
> hmm ok, i will get back to you when its done

i was able to successfully patch and build dwm again without the `dwm-statuscmd-6.2.diff patch`. but im unable too login now whenever i enter my password and login in sddm it just says there with frozen sddm screen i can move the mouse though.

 i tried nested xephyr session but it also failed gave me this output - 
```
dwm: fatal error: request code=70, error code=8
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  70 (X_PolyFillRectangle)
  Serial number of failed request:  88
  Current serial number in output stream:  89
```

**Comment by Abh15h3k** [comment]
what all patches did u apply?

**Comment by apoorv569** [comment]
> what all patches did u apply?

alpha, attachaside, autostart, bar-height, centeredmaster, hide-vacant-tags, restartsig, rotatestack, statuscmd-signal, sticky, systray and dwmblocks-statuscmd

**Comment by Abh15h3k** [comment]
> > > i would recommend re do everything. those 2 patches have alot of common code.
> > 
> > 
> > hmm ok, i will get back to you when its done
> 
> i was able to successfully patch and build dwm again without the `dwm-statuscmd-6.2.diff patch`. but im unable too login now whenever i enter my password and login in sddm it just says there with frozen sddm screen i can move the mouse though.
> 
> i tried nested xephyr session but it also failed gave me this output -
> 
> ```
> dwm: fatal error: request code=70, error code=8
> X Error of failed request:  BadMatch (invalid parameter attributes)
>   Major opcode of failed request:  70 (X_PolyFillRectangle)
>   Serial number of failed request:  88
>   Current serial number in output stream:  89
> ```
> 
> just to be sure i tried the old dwm build that was working through xephyr is worked fine,

systray patch is cause that error. i'm not sure why yet. 
but do you really need it? its redundant if your using dwmblocks

**Comment by apoorv569** [comment]
> > > > i would recommend re do everything. those 2 patches have alot of common code.
> > > 
> > > 
> > > hmm ok, i will get back to you when its done
> > 
> > 
> > i was able to successfully patch and build dwm again without the `dwm-statuscmd-6.2.diff patch`. but im unable too login now whenever i enter my password and login in sddm it just says there with frozen sddm screen i can move the mouse though.
> > i tried nested xephyr session but it also failed gave me this output -
> > ```
> > dwm: fatal error: request code=70, error code=8
> > X Error of failed request:  BadMatch (invalid parameter attributes)
> >   Major opcode of failed request:  70 (X_PolyFillRectangle)
> >   Serial number of failed request:  88
> >   Current serial number in output stream:  89
> > ```
> > 
> > 
> > just to be sure i tried the old dwm build that was working through xephyr is worked fine,
> 
> systray patch is causing that error. i'm not sure why yet. mostly its clashing with changes made by the other patches.
> but do you really need it? its redundant if your using dwmblocks

i use it for few apps that req systray. nextcloud and syncthing mainly.

**Comment by Abh15h3k** [comment]
well. the thing is the systray patch is one of those patches that change existing code ( most patches just add without changing existing code ). so thats probably why its giving errors.

if i use only the systray patch on a fresh dwm clone it works. but it will break (itself and other patches) when other patches are applied.

**Comment by apoorv569** [comment]
> well. the thing is the systray patch is one of those patches that change existing code ( most patches just add without changing existing code ). so thats probably why its giving errors.
> 
> if i use only the systray patch on a fresh dwm clone it works. but it will break (itself and other patches) when other patches are applied.

i removed the lines from `dwm-statuscmd-6.2.diff` from my previous build that was working and rebuild it. im able to log in now. but clicking still doesn't work

**Comment by Abh15h3k** [comment]
could u compress you dwm source folder and send it to me somehow?

**Comment by apoorv569** [comment]
> could u compress you dwm source folder and send it to me somehow?

https://drive.google.com/drive/folders/1WAeujcjMuHNgmdrgN7RoRvgVEdUbTh3J?usp=sharing, https://drive.google.com/drive/folders/1Yc32bdHOiyNEUBOEMGhO3UT-jm07I5lH?usp=sharing

**Comment by Abh15h3k** [comment]
1. your dwmblocks did not have the `dwmblocks-statuscmd.diff` ( from the statuscmd patches ).
2. like i said earlier using systray would break other patches. what was happening was that systray was grabbing the click.

apply this patch to your dwmblocks https://pastebin.com/Pv8ExaJa (clickable_dwmblocks.diff)
apply this patch to your dwm https://pastebin.com/Ws6Ks60B (dwm_fix.diff)

you do not need to apply `dwmblocks-statuscmd.diff` seperatly i have included it `clickable_dwmblocks.diff`

also for the clickable functionality to work your blocks.h must contain path to a script. direct commands wont do anything.

**Comment by apoorv569** [comment]
>     1. your dwmblocks did not have the `dwmblocks-statuscmd.diff` ( from the statuscmd patches ).
> 
>     2. like i said earlier using systray would break other patches. what was happening was that systray was grabbing the click.
> 
> 
> apply this patch to your dwmblocks https://pastebin.com/Pv8ExaJa (clickable_dwmblocks.diff)
> apply this patch to your dwm https://pastebin.com/Ws6Ks60B (dwm_fix.diff)
> 
> you do not need to apply `dwmblocks-statuscmd.diff` seperatly i have included it `clickable_dwmblocks.diff`
> 
> also for the clickable functionality to work your blocks.h must contain path to a script. direct commands wont do anything.

i patched the patches you sent i had to patch `dwm_fix.diff` manually the included line number according to my `dwm.c` was incorrect so it failed i commented out those lines. still nothing.

**Comment by apoorv569** [comment]
>     1. your dwmblocks did not have the `dwmblocks-statuscmd.diff` ( from the statuscmd patches ).
> 
>     2. like i said earlier using systray would break other patches. what was happening was that systray was grabbing the click.
> 
> 
> apply this patch to your dwmblocks https://pastebin.com/Pv8ExaJa (clickable_dwmblocks.diff)
> apply this patch to your dwm https://pastebin.com/Ws6Ks60B (dwm_fix.diff)
> 
> you do not need to apply `dwmblocks-statuscmd.diff` seperatly i have included it `clickable_dwmblocks.diff`
> 
> also for the clickable functionality to work your blocks.h must contain path to a script. direct commands wont do anything.

i patched the patches you sent i had to patch `dwm_fix.diff` manually the included line number according to my `dwm.c` was incorrect so it failed i commented out those lines. still nothing.

some of the blocks are direct commands they came by default in that file, but the other are script and i have given the path to the scripts folder `~/.local/bin/statusbar` i created that directory and put those scripts there.

**Comment by Abh15h3k** [comment]
I just re-downloaded your dwm and dwmblocks source folders from the drive links you sent. applied my patches ( 2 hunks fail in `dwm.c`, but they don't matter cause its just removing and adding blank lines) i installed them. logged out and logged in. it works for me.

just to make sure. clicks will work only if you have path to a executable script in blocks.h and updated signal has to be unique. no two or more blocks should have the same signal number.

and the script should be in this format.

```
#!/bin/sh

case $BLOCK_BUTTON in
    1) #left click action here
        ;;
    2) #  middle click action here
        ;;
    3) # right click action here
        ;;
esac

#normal block commands here
```
note: you can have direct commands in blocks.h. but nothing will happen when you click those blocks.

following these points. i am able to get clickable dwmblocks working using your sources codes.
not much more can do at this point

**Comment by apoorv569** [comment]
> EDIT: I remember having asked you to change `$BLOCK_BUTTON` to `$BUTTON`. if u have that change in place. undo it.
> 
> I just re-downloaded your dwm and dwmblocks source folders from the drive links you sent. applied my patches ( 2 hunks fail in `dwm.c`, but they don't matter cause its just removing and adding blank lines) i installed them. logged out and logged in. it works for me.
> 
> just to make sure. clicks will work only if you have path to a executable script in blocks.h and updated signal has to be unique. no two or more blocks should have the same signal number.
> 
> and the script should be in this format.
> 
> ```
> #!/bin/sh
> 
> case $BLOCK_BUTTON in
>     1) #left click action here
>         ;;
>     2) #  middle click action here
>         ;;
>     3) # right click action here
>         ;;
> esac
> 
> #normal block commands here
> ```
> 
> note: you can have direct commands in blocks.h. but nothing will happen when you click those blocks.
> 
> following these points. i am able to get clickable dwmblocks working using your sources codes.
> not much more can do at this point

well i downloaded my own folder i sent you. patched with the patches you sent me. there are some direct commands in there i know, but the volume, battery and clock scripts im using in `blocks.h` are the scripts i grabbed from luke's repo, i did not edit them in anyway.

now after logging in clicking volume and battery does nothing still. but clicking on clock is working now its a notification with month calender. any idea why the volume and battery are not working? i have the req package for volume script `pulsemixer` installed already.

**Comment by Abh15h3k** [comment]
> anyway to fix the positioning
>im guessing its because i have 1 icon in systray its causing the position issue.

i wouldn't know.

> and how/where do i set default $TERMINAL and $EDITOR variables to what i want

you can set those in ~/.profile and ~/.bashrc ( if you are using bash ) or ~/.zshrc ( if you are using zsh )

**Comment by apoorv569** [comment]
> > anyway to fix the positioning
> > im guessing its because i have 1 icon in systray its causing the position issue.
> 
> i wouldn't know.
> 
> > and how/where do i set default $TERMINAL and $EDITOR variables to what i want
> 
> you can set those in ~/.profile and ~/.bashrc ( if you are using bash ) or ~/.zshrc ( if you are using zsh )

anyway, thanx alot dude for bearing with me. you helped me. i will figure out the rest :D
thanks
