### ISSUE TITLE
Flickering when updating dwmblocks

### ISSUE THREAD

**Issue by constatinus** [LukeSmithxyz/dwmblocks#32]
Heres the `config.h`:
```
static const Block blocks[] = {
	/*Icon*/	/*Command*/		/*Update Interval*/	/*Update Signal*/
	{"📡", "/home/user/.local/bin/statusbar/network", 6, 12},
	{"💽", "/home/user/.local/bin/statusbar/storage", 45, 13},
	{"💡", "/home/user/.local/bin/statusbar/backlight", 5, 14},
	{"🔊", "/home/user/.local/bin/statusbar/volume", 5, 10},
	{"", "/home/user/.local/bin/statusbar/keyboard", 5, 16},
	{"RAM:", "/home/user/.local/bin/statusbar/memory", 8, 17},
	{"🔋", "/home/user/.local/bin/statusbar/battery", 10, 18},
	{"", "/home/user/.local/bin/statusbar/date", 30, 19}
};

static char *delim = " ";
```
And also here are the following commands that are being executed when updating brightness and the volume:
`pamixer -i 2; kill -44 $(pidof dwmblocks)`, `/home/user/.local/bin/scripts/backlight inc; kill -48 $(pidof dwmblocks)`
`/home/user/.local/bin/scripts/backlight`:
```
#!/bin/dash
if [ $(xbacklight | sed 's/\..*//') -le 1 ]; then
	if [ "$1" = "inc" ]; then
		xbacklight -inc 0.1 &
	elif [ "$1" = "dec" ]; then
		xbacklight -dec 0.1 &
	fi
elif [ $(xbacklight | sed 's/\..*//') -le 6 ]; then
	if [ "$1" = "inc" ]; then
		xbacklight -inc 0.5 &
	elif [ "$1" = "dec" ]; then
		xbacklight -dec 0.5 &
	fi
else
	if [ "$1" = "inc" ]; then
		xbacklight -inc 5 &
	elif [ "$1" = "dec" ]; then
		xbacklight -dec 5 &
	fi
fi
```
`time backlight inc` usualy wanders around 0.03 secs, while `time (pamixer -i 2; kill -44 $(pidof dwmblocks))` around 0.015, not much of a difference.
When changing the brightness this way via dwm keybindings, everything works fine. The issue is, when changing the volume this way dwmblocks tends to 'flicker'. Some modules tend to dissapear for a moment, especially the network module, ram, backlight and the keyboard module. Like they never existed (for a moment only of course). The date module (and also the storage one) does not flicker almost at all, however when i lower its update interval to something like 1, it also undergoes the same process. Seems like the lower their interval is the more likely they are to flicker when dwmblocks is being signaled.
Same issue happens on torrinfails dwmblocks.

**Comment by mlscarlson** [comment]
I am having the same problem and I am using custom scripts. I have my volume module set so that I can adjust the percentage via scroll wheel and when I do so it causes my statusbar to "flicker" as you described.

The issue probably lies somewhere in dwmblocks.c. The issue is that a lot of the code isn't commented so it's hard to tell what function does what exactly.

I tried modifying the sleep() time in statusloop() since that's the only thing that stood out to me in a quick skim of the code but it didn't seem to do anything.

It's not really a big deal since my dwm shortcuts work just as yours are, but it'd be nice to have a stable bar nevertheless.

**Comment by mkhattat** [comment]
I also have the same issue with the volume module. When I adjust the percentage via scroll wheel, it causes the status bar to flicker. It was really annoying.

So I used a dirty hack to work around the issue.

I added the following line at the end of the ```void getcmd(const Block *block, char *output)``` function:
```c
nanosleep((const struct timespec[]){{0, 50000000L}}, NULL);
```
of course you have to include ```time.h```:
```c
#include <time.h>
```

This causes a small delay, 50ms, between updates of each block but it is enough not to cause the status bar to flicker. You, however, may want to change its value.

I also increased the steps in the volume script.

But I hope there will be a fix in upstream.

**Comment by mkhattat** [comment]
I also have the same issue with the volume module. When I adjust the percentage via scroll wheel, it causes the status bar to flicker. It was really annoying.

So I used a dirty hack to work around the issue.

I added the following line at the end of the ```void getcmd(const Block *block, char *output)``` function:
```c
nanosleep((const struct timespec[]){{0, 50000000L}}, NULL);
```
of course you have to include ```time.h```:
```c
#include <time.h>
```

This causes a small delay, 50ms, between updates of each block but it is enough not to cause the status bar to flicker. You, however, may want to change its value.

I also increased the steps in the volume script.

But I hope there will be a fix in the upstream branch.

**Comment by mkhattat** [comment]
I also have the same issue with the volume module. When I adjust the percentage via scroll wheel, it causes the status bar to flicker. It was really annoying.

So I used a dirty hack to work around the issue.

I added the following line at the end of the ```void getcmd(const Block *block, char *output)``` function in ```dwmblocks.c```:
```c
nanosleep((const struct timespec[]){{0, 50000000L}}, NULL);
```
of course you have to include ```time.h```:
```c
#include <time.h>
```

This causes a small delay, 50ms, between updates of each block but it is enough not to cause the status bar to flicker. You may, however, want to change its value.

I also increased the steps in the volume script.

But I hope there will be a fix in the upstream branch.

**Comment by mlscarlson** [comment]
> I also have the same issue with the volume module. When I adjust the percentage via scroll wheel, it causes the status bar to flicker. It was really annoying.
> 
> So I used a dirty hack to work around the issue.
> 
> I added the following line at the start of the `void getcmd(const Block *block, char *output)` function in `dwmblocks.c`:
> 
> ```c
> nanosleep((const struct timespec[]){{0, 50000000L}}, NULL);
> ```
> 
> of course you have to include `time.h`:
> 
> ```c
> #include <time.h>
> ```
> 
> This causes a small delay, 50ms, between updates of each block but it is enough not to cause the status bar to flicker. You may, however, want to change its value.
> 
> I also increased the steps in the volume script.
> 
> But I hope there will be a fix in the upstream branch.

Yup, this works. I knew it had something to do with time but wasn't exactly sure how to approach the issue.

A delay of 100ms is enough for the status bar to neither flicker nor create duplicate/blank modules in my case. The time delay is very slight and is barely noticeable.

Thanks mate!

**Comment by constatinus** [comment]
Works as well, 90ms for me

**Comment by UtkarshVerma** [comment]
This issue was really bothering me so I fixed up the code. The issue was caused because the signal handlers were using `printf()` and `fgets()` which aren't [signal-safe](https://man7.org/linux/man-pages//man7/signal-safety.7.html). I had to make other modifications to the code, so instead of making a PR for this, I created a new repo:
https://github.com/UtkarshVerma/dwmblocks
