### ISSUE TITLE
Volume always show 100% I use an external monitor.

### ISSUE THREAD

**Issue by sleeperzjf** [LukeSmithxyz/dwmblocks#34]
When I use an external monitor my `volume` module always shows `100%`.

The `sed` command `sed "s,.* \([0-9]\+\)%.*,\1,;1q"` show match the line including `volume` number and replace it with the number it gets if I'm not wrong.

But the information after `grep` I get looks like this:
![image](https://user-images.githubusercontent.com/65698607/84588593-5fc19300-ae5b-11ea-8f1e-eeb40451f25d.png)
Should I change some settings about the external monitor or should I change the script?

**Comment by sleeperzjf** [comment]
And how to change the primary monitor in `dwm`?

**Comment by LukeSmithxyz** [comment]
Fixed in efbc3f3de37e745fc8e55104e46433060f84cb52. Make sure `pamixer` is installed.
