### ISSUE TITLE
colored emoji not showing.

### ISSUE THREAD

**Issue by apoorv569** [LukeSmithxyz/dwmblocks#37]
my dwmblocks is not showing colored emoji's, i have installed `libxft-bgra` for the AUR, they were showing fine until yesterday, today i logged in and colored emoji's are not showing some are showing as squares and some are black and white. i have `ttf-joypixels` and `noto-fonts-emoji` installed as well. i have removed these lines also in `drw.c`
```
FcBool iscol;
	if(FcPatternGetBool(xfont->pattern, FC_COLOR, 0, &iscol) == FcResultMatch && iscol) {
		XftFontClose(drw->dpy, xfont);
		return NULL;
	}
```
https://imgur.com/wInwczA

**Comment by apoorv569** [comment]
i got it working, i added the font in `config.h` and its showing now. i recently added a patch maybe that messed up the `config.h`

**Comment by Jennemeister** [comment]
Could you perhaps elaborate? I have this same issue, but I'm unsure how you added it to the header file. Did you add it as in dwm's config.h file?

**Comment by apoorv569** [comment]
> Further research solved my problem :)

I mean the section in `config.h` where you specify which fonts to use
```
static const char *fonts[]          = { "Mononoki Nerd Font:size=10:antialias=true:autohint=true",
                                           "JoyPixels:size=10:antialias=true:autohint=true",
                                           "Noto Fonts Emoji=10:antialias=true:autohint=true" };
```
added joy pixels and noto fonts emoji, and its working now
