### ISSUE TITLE
BLOCK_BUTTON issue

### ISSUE THREAD

**Issue by atticus-sullivan** [LukeSmithxyz/dwmblocks#4]
Hi there,
am I the only one where the mechanism with the BLOCK_BUTTON does not work? (the actions specified in the case $BLOCK_BUTTON are not executed)
In addition, when I do a mousewheel click a terminal is opened (st) which definitely should not happen. 

Are these Bugs or is there something wrong with my clone?
(and I think maybe one should add an explanation for the BLOCK_BUTTON mechanism which as I think makes it possible to react to clicks depending on which block it it clicked)

**Comment by LukeSmithxyz** [comment]
BLOCK_BUTTON is only for i3blocks. The dwm version doeesn't use it at
all. I suppose I wouldn't mind building click functionality into
dwm/dwmblocks so I could use them, but I've never really looked into it.

Either way, it's not an error. It's just not a feature yet.

**Comment by atticus-sullivan** [comment]
Ah ok then its fine, still I'm wondering whether it's on purpose that on a mousewheel click a new terminal is opened and if it's possible to disable that? (I don't like it since I see no point in doing that)

**Comment by LukeSmithxyz** [comment]
Huh, I never noticed that. I didn't put it in my self, so it must have come from some patch as an additional feature that I never edited. It's not part of dwmblocks though, but dwm.

**Comment by atticus-sullivan** [comment]
xD I too didn't notice that until now when I tried to test the feature to klick on the blocks. But as you mentioned this works with another statubar too so it has to be a dwm thing (not a dwmblocks thing)

So thanks for your quick responses ;)

**Comment by luukvbaal** [comment]
This can be achieved with the [statuscmd](https://dwm.suckless.org/patches/statuscmd/) patch for dwm.
Use e.g. `printf '%b %s' "\3" "$(date '+%A %d %b %H:%M')"` as the `clock` script and clicking on it will launch the third (indicated by the `"\3"` octal escape printed by `printf %b`) command defined in `static const char *statuscmds[]` in `dwm`'s config.h.

If you use the original statusbar scripts in `statuscmds[]` and change `case $BUTTON in` to `case ${BUTTON:-$BLOCK_BUTTON} in` the scripts should maintain portability for both `dwm` and `i3` I suppose.

I'm currently converting my statusbar scripts but I'm afraid my scripts have strayed too far from Luke's for a pull request.

**Comment by LukeSmithxyz** [comment]
Interesting. I haven't noticed that patch, but I'll try it out.
Depending on how it works, it might be better than having that separate
dwmblocks program.

**Comment by luukvbaal** [comment]
I use it in combination with `dwmblocks`, to keep signal handling. Or did you mean having the click handling done by `dwmblocks`, by "it might be better than having that separate
dwmblocks program."? Not sure what you meant there, but yeah it works fine on my end after converting the scripts. It amounts to populating `statuscmds[]` in `dwm's` `config.h`, and adding the `%b` and the appropriate `\x`  to the `printf` commands.

Regarding `i3` portability you could also just change the patch to export the button pressed as `$BLOCK_BUTTON`(single line change). Just not sure what `i3blocks` will do the with extra byte printed by `printf`.

**Comment by LukeSmithxyz** [comment]
The author of that patch contacted me several days ago and after a back-and-forth put out what I think is a very nice and streamlined version of that  patch without the silliness of adding a list of commands to dwm's sourcecode and printing extra sequences and such.

Just install these on dwm and dwmblocks and it treats `$BUTTON` the same as `$BLOCK_BUTTON` in i3.

https://gist.github.com/danbyl/54f7c1d57fc6507242a95b71c3d8fdea

I have now bulid this into my build with the only additional change being that it uses the variable `$BLOCK_BUTTON` to maintain compatibility with the i3 scripts.
