### ISSUE TITLE
Forking - updates status before/at same time as child:  Weather module disappears

### ISSUE THREAD

**Issue by rjl6789** [LukeSmithxyz/dwmblocks#41]
Hi,

I noticed that if I try to update the weather module by middle clicking... it disappears from the bar. (can get it back by sending the relevant signal (39).)

I might be barking up the wrong tree here:

- but I believe this is caused by the fact that when the `buttonhandler` function is called it forks the block command call (I'm guessing if slow internet, cpu, prevent a block crash affecting rest of bar etc)

- The parent continues though and runs the `getsigcmds` function - as the fork is already getting the weather update - I think `getsigcmds`->`getcmds` tries to get the update as well - and either bombs out or returns updating the `statusstr` variable as blank for the weather block.

I thought about adding a `wait` for the fork - but then this negates the point of the fork.

Sorry, having trouble fixing this one.  Any ideas?

**Comment by rjl6789** [comment]
Hi,
I think the behaviour desired is that when you button click the program forks - ideally you want to be able to use the bar whilst the commands being run in the fork complete, but then once the fork is finished, the bar updates.  At the moment I think the parent updates regardless of whether the fork is complete - in my case the timing is such that it updates the weather block mid-download with an empty file and so the block disappears.

I think this may also be related to the problem that the pull request #38 tries to "fix" (I don't think this is a real fix though - moving the lines just updates the statusbar before the button click command is executed - the bar then doesn't update until a second click or signal is sent)

I don't know how this can be done neatly, or if I'm understanding how things work so rather than putting in a pull request please see a simple patch below that "seems" to work for me. I just send the update signal as part of the forks shell command.

Is this worth putting in a pull request?  It seems to fix the issue?

``` 
diff --git a/dwmblocks.c b/dwmblocks.c
index d135a7d..68267d7 100644
--- a/dwmblocks.c
+++ b/dwmblocks.c
@@ -193,6 +193,7 @@ void sighandler(int signum)
 void buttonhandler(int sig, siginfo_t *si, void *ucontext)
 {
 	char button[2] = {'0' + si->si_value.sival_int & 0xff, '\0'};
+	pid_t process_id = getpid();
 	sig = si->si_value.sival_int >> 8;
 	if (fork() == 0)
 	{
@@ -203,14 +204,14 @@ void buttonhandler(int sig, siginfo_t *si, void *ucontext)
 			if (current->signal == sig)
 				break;
 		}
-		char *command[] = { "/bin/sh", "-c", current->command, NULL };
+		char shcmd[1024];
+		sprintf(shcmd,"%s && kill -%d %d",current->command, current->signal+34,process_id);
+		char *command[] = { "/bin/sh", "-c", shcmd, NULL };
 		setenv("BLOCK_BUTTON", button, 1);
 		setsid();
 		execvp(command[0], command);
 		exit(EXIT_SUCCESS);
 	}
-	getsigcmds(sig);
-	writestatus();
 }
 
 #endif
```

**Comment by sanicSanic** [comment]
hey I have same issue over blocks disappearing when scroll happens.

but after choking the "getcmd" with a semaphore , mine now works better,

still I got the problem of first block somehow rendering over last block.

/* ccc:*/
sem_t getcmd_sem;

void getcmd(const Block * block , char * output) {

        /*
                to avoid multiple getcmd writing to the same output
                when they are executed in a burst, semaphore is used.
                they first read to a local variable to make sure it is safe.
         */
        sem_wait(&getcmd_sem);

        char cmdReturn[CMDLENGTH];
        FILE *cmdf = popen(block->command,"r");
        if(!cmdf) {
                sem_post(&getcmd_sem);
                printf("\n\npfile Exit\n\n");
                return ;
        }
        fgets( cmdReturn , CMDLENGTH , cmdf );
        pclose(cmdf);
        // to avoid the diseapear of block, not updating when cmd return nothing.
        if(*cmdReturn=='\0') {
                sem_post(&getcmd_sem);
                printf("\n\ncmd emty Exit\n\n");
                return;
        }
        // updating output string
        if(block->signal) {
                output[0]=block->signal;
                output++;
        }
        strcpy(output, block->icon);
        int i = strlen(block->icon);
        strcpy(output + i  ,cmdReturn);
        remove_all(output , '\n');
        i = strlen(output);

        if(block!=&blocks[LENGTH(blocks)-1])
                strcat(output, delim);
        i+=strlen(delim);
        output[i++]='\0';


        sem_post(&getcmd_sem);
}
//

**Comment by sanicSanic** [comment]
> Hi,
> I think the behaviour desired is that when you button click the program forks - ideally you want to be able to use the bar whilst the commands being run in the fork complete, but then once the fork is finished, the bar updates. At the moment I think the parent updates regardless of whether the fork is complete - in my case the timing is such that it updates the weather block mid-download with an empty file and so the block disappears.
> 
> I think this may also be related to the problem that the pull request #38 tries to "fix" (I don't think this is a real fix though - moving the lines just updates the statusbar before the button click command is executed - the bar then doesn't update until a second click or signal is sent)
> 
> I don't know how this can be done neatly, or if I'm understanding how things work so rather than putting in a pull request please see a simple patch below that "seems" to work for me. I just send the update signal as part of the forks shell command.
> 
> Is this worth putting in a pull request? It seems to fix the issue?
> 
> ```
> diff --git a/dwmblocks.c b/dwmblocks.c
> index d135a7d..68267d7 100644
> --- a/dwmblocks.c
> +++ b/dwmblocks.c
> @@ -193,6 +193,7 @@ void sighandler(int signum)
>  void buttonhandler(int sig, siginfo_t *si, void *ucontext)
>  {
>  	char button[2] = {'0' + si->si_value.sival_int & 0xff, '\0'};
> +	pid_t process_id = getpid();
>  	sig = si->si_value.sival_int >> 8;
>  	if (fork() == 0)
>  	{
> @@ -203,14 +204,14 @@ void buttonhandler(int sig, siginfo_t *si, void *ucontext)
>  			if (current->signal == sig)
>  				break;
>  		}
> -		char *command[] = { "/bin/sh", "-c", current->command, NULL };
> +		char shcmd[1024];
> +		sprintf(shcmd,"%s && kill -%d %d",current->command, current->signal+34,process_id);
> +		char *command[] = { "/bin/sh", "-c", shcmd, NULL };
>  		setenv("BLOCK_BUTTON", button, 1);
>  		setsid();
>  		execvp(command[0], command);
>  		exit(EXIT_SUCCESS);
>  	}
> -	getsigcmds(sig);
> -	writestatus();
>  }
>  
>  #endif
> ```

I dont think there is problem with the buttonhandler

**Comment by LukeSmithxyz** [comment]
Okay. I've added that fix.
