### ISSUE TITLE
dwmblocks freezes at seemingly random intervals = zsh: unknown signal dwmblocks

### ISSUE THREAD

**Issue by BadBrush** [LukeSmithxyz/dwmblocks#43]
when I have dwmblocks running in a terminal I get "zsh: unknown signal dwmblocks"
I'm guessing the issue is similar to #16 

I've tried commenting out all the modules except for the clock and internet but I still have this issue. 
Is there a way to figure out which is the offending signal and where this error lies?

```
//Modify this file to change what commands output to your statusbar, and recompile using the make command.
static const Block blocks[] = {
	/*Icon*/	/*Command*/		/*Update Interval*/	/*Update Signal*/
	{"", "cat /tmp/recordingicon 2>/dev/null",	0,	9},
	{"",	"music",	0,	11},
	/* {"",	"pacpackages",	0,	8}, */
	/* {"",	"news",		0,	6}, */
	/* {"",	"crypto",	0,	13}, */
	/* {"",	"price bat \"Basic Attention Token\" 🦁",	0,	20}, */
	/* {"",	"price btc Bitcoin 💰",				0,	21}, */
	/* {"",	"price lbc \"LBRY Token\" 📚",			0,	22}, */
	/* {"",	"torrent",	20,	7}, */
	/* {"",	"memory",	10,	14}, */
	/* {"",	"cpu",		10,	18}, */
	/* {"",	"moonphase",	18000,	17}, */
	{"",	"weather",	18000,	5},
	{"",	"mailbox",	180,	12},
	{"",	"nettraf",	1,	16},
	{"",	"volume",	0,	10},
	{"",	"clock",	60,	1},
	{"",	"internet",	5,	4},
	/* {"",	"help-icon",	0,	15}, */
};

//sets delimeter between status commands. NULL character ('\0') means no delimeter.
static char *delim = " ";

// Have dwmblocks automatically recompile and run when you edit this file in
// vim with the following line in your vimrc/init.vim:

// autocmd BufWritePost ~/.local/src/dwmblocks/config.h !cd ~/.local/src/dwmblocks/; sudo make install && { killall -q dwmblocks;setsid dwmblocks & }

```

**Comment by BadBrush** [comment]
I seem to be still having this problem, I'm not even quite sure how to troubleshoot this issue.

dwmblocks 2> error_log      just gives me the unknown signal

If anyone can help me with troubleshooting this and finding where the problem is coming from I would really appreciate it, thank you.

**Comment by LukeSmithxyz** [comment]
Do you have the update that was added today?

What signal are you sending to it and with what specific command?

**Comment by BadBrush** [comment]
I didn't have the newest update, I'm trying with it now and so far so good. I'm keeping a terminal open running to dwmblocks to check for errors and I'll wait and see if anything pops up. Hopefully the new update has resolved the issue.

As for the signal, I can't think of any signal I'm sending to dwmblocks that could be causing the crash. I had a mailbox check signal sent through my crontab but even after disabling that it still occurred.
