### ISSUE TITLE
[1]    6990 segmentation fault (core dumped)  dwmblocks

### ISSUE THREAD

**Issue by Wjinlei** [LukeSmithxyz/dwmblocks#44]
[1]    6990 segmentation fault (core dumped)  dwmblocks

**Comment by Wjinlei** [comment]
I will close this question, I have solved it, thank you.

**Comment by eriteric** [comment]
@Wjinlei How did you fix it?

**Comment by Wjinlei** [comment]
@eriteric 

> @Wjinlei How did you fix it?

It is already two years ago, I also don't remember, I have been using the https://github.com/torrinfail/dwmblocks now

**Comment by eriteric** [comment]
@Wjinlei ok, thank you for the reply
