### ISSUE TITLE
[Solved] Missing the misc block (systray)? (block containing misc icons such as messagers)

### ISSUE THREAD

**Issue by MYDavoodeh** [LukeSmithxyz/dwmblocks#45]
Hello, I'm pretty noob in this so yeah. I'm sorry!

i3blocks had this misc section at the beginning of the bar which was populated by misc icons such as messengers, other programs (like Steam) and so forth.
I noticed that dwmblocks doesn't have such block and I couldn't find any patch or guide to enable it.

Any idea on what to do? I'm afraid I don't know C that much to write it on my own. So keep it noob friendly, please.
Pardon me for my poor English.

**Comment by build2stone** [comment]
For that you'll want to apply this patch to dwm: https://dwm.suckless.org/patches/systray/

**Comment by MYDavoodeh** [comment]
Thank you a lot that fixed it. @build2stone 

For newbies like me who have difficulties with applying (it won't apply cleanly to Luke's build `dwm.c`):
I made another patch which is "Luke compatible".
Just set the variables below to your `config.h`:
```c
static const unsigned int systraypinning = 0;   /* 0: sloppy systray follows selected monitor, >0: pin systray to monitor X */
static const unsigned int systrayspacing = 2;   /* systray spacing */
static const int systraypinningfailfirst = 1;   /* 1: if pinning fails, display systray on the first monitor, False: display systray on the last monitor*/
static const int showsystray        = 1;        /* 0 means no systray */
```

and apply the patch below and you are ready to go:
```
curl -OL https://raw.githubusercontent.com/MYDavoodeh/dotfiles/renew/.config/etc/dwm/dwm-systray-20200610-f09418b--luke-20200806-484720b.diff
patch < dwm-systray-20200610-f09418b--luke-20200806-484720b.diff
```

P.S: I'm not sure if I update the patch or keep it permanently!
