### ISSUE TITLE
using dwmblocks cause lags of dwm window switching

### ISSUE THREAD

**Issue by sanicSanic** [LukeSmithxyz/dwmblocks#49]
I have newly installed Luke's build of dwm and dwmblocks (no other patches yet).
when I started desktop without dwmblocks, switching around was just super fast.

once dwmblocks start , the hole desktop just lags a bit , and switching become slower.

but killing dwmblocks and running "xsetroot -name 'blablabla' " just recovers it.

using none emoji and none scheme color changing also has the same problem. htop shows minimum cpu usage.

does any one feels the lag as well? This problem probably also exists in other build.

**Comment by sanicSanic** [comment]
oh I find out I had pass the dwm chars less than white space for scheme color modding,
This cause lots of lags, after getting rid of it everything get fixed up.

**Comment by scrouthtv** [comment]
@sanicSanic can you explain what exactly you changed? I'm also experiencing performance issues using dwmblocks

**Comment by scrouthtv** [comment]
For anyone who is experiencing a similar issue:
My problem was that dwmblocks was putting non printable text into the status bar (e. g. "\n").
I fixed it by installing https://dwm.suckless.org/patches/statuscmd/
(https://dwm.suckless.org/patches/statuscmd/dwm-statuscmd-signal-6.2.diff)

If you look into the patch, the author introduces a function that filters the status bar content for those characters and removes them.
I didn't need the dwmblocks-statuscmd.diff patch
