### ISSUE TITLE
Bar is not updating at startup after suspend

### ISSUE THREAD

**Issue by vedang-jammy** [LukeSmithxyz/dwmblocks#54]
I always keep my laptop suspended while it's not in use. But when I start the laptop from suspending it freezes and only shows status before suspending. 
I can't figure out what's the solution for this.
I appreciate the help in this issue.

**Comment by nghiapq77** [comment]
You could have your init system run a script after suspend.

**Comment by vedang-jammy** [comment]
Thanks for help but I actually switched to qtile
