### ISSUE TITLE
dwm blocks crash every once in a while even cronjobs are all disabled

### ISSUE THREAD

**Issue by eGredius** [LukeSmithxyz/dwmblocks#55]
Hi,

I was wondering about this "crashing" / "freezing" issue of the blocks. If I run `crontab -l` it outputs `no crontab for usrname`. And there is no items left in those `/etc/cron.hourly`, `/etc/cron.daily`, `/etc/cron.weekly`, `/etc/cron.monthly` directories.

This, I suppose, means that there is no unexpected signals sent to the blocks? However it freezes every once in a while and the dwm needs to be renewed.

Thanks for any advice in advance!

**Comment by LukeSmithxyz** [comment]
Are you sure there's not some other script you have that tries to update an unused module? Mail, volume, etc?

**Comment by eGredius** [comment]
lol looks like it's the newsboat keybindings that I overlooked. My bad!

**Comment by eGredius** [comment]
Thanks Luke!
