### ISSUE TITLE
Weird characters

### ISSUE THREAD

**Issue by shunlog** [LukeSmithxyz/dwmblocks#57]
![bar](https://user-images.githubusercontent.com/48106195/99526518-062e3900-29a4-11eb-9f19-0d8159fd6eea.png)

The characters underlined in red are not supposed to be there. The block scripts output comes after the bookmark icon, so the problem is not in them.

My config.h file:
```c
static const Block blocks[] = {
	{"",	"dwm-volume",	0,	10},
	{"",	"dwm-battery",	5,	3},
	{"",	"dwm-clock",	60,	1},
};
static char *delim = "|";
```

**Comment by LukeSmithxyz** [comment]
Did you install the statuscmd patch on dwm?

https://dwm.suckless.org/patches/statuscmd/

**Comment by shunlog** [comment]
That fixed it. From the way it was put in the readme I thought that step is optional.
