### ISSUE TITLE
Multithreading Possible?

### ISSUE THREAD

**Issue by tramhao** [LukeSmithxyz/dwmblocks#59]
I'm using this build and up to now very good. A little problem though. When login, there are 2 scripts hold the whole dwmblocks back. One is pacpackage and the other is openweathermap( I use this one instead of wttr.in because it's realtime temperature). 
Is it possible to update these 2 modules later? 
I saw a multithreading pull request in original github, but wasn't accepted yet.
https://github.com/torrinfail/dwmblocks/pull/34
Thanks.

**Comment by keikari** [comment]
Hi, I don't think it will ever get accepted.
I just send pull request so people who need multi thread feature can find it.
I'm not a programmer, so code there might not meet all beauty standards, but it should still run as expected(for me it has) and I try to keep adding fixes that get accepted to dwmblocks itself to keep it up-to-date.

**Comment by tramhao** [comment]
https://github.com/ashish-yadav11/dwmblocks

This one seems like a better upstream.

**Comment by tramhao** [comment]
I figured out a way to solve this problem. Basically I just use cron jobs to update status like mail, news, pacpackages and weather, and then write the states to tmp folder. After that, the status bar scripts just read these files and print result. So there is no delay when start dwm because all these time consuming jobs are executed by cron, not dwmblocks. 
For anyone have this problem, you can check out my repo for details.
https://github.com/tramhao/dotfiles-ladm
Please check 2 folders:
.local/bin/cron
.local/bin/statusbar
