### ISSUE TITLE
Emoji's like reload RSS do not dissepier even when they should.

### ISSUE THREAD

**Issue by kmj9** [LukeSmithxyz/dwmblocks#65]
After last commit scripts like newsup, mailsync makes emoji stay in the bar even there's 0 RSS, 0 new mail and or 0 new packeges

**Comment by tramhao** [comment]
same here. 
```
git checkout 141e5f45ed793a8a133b2d40d99f11e127a73bb7 -- dwmblocks.c                                                         
```
then make install fix the problem for me.
