### ISSUE TITLE
feature request : Use of siji Icons

### ISSUE THREAD

**Issue by jamesclarke28** [LukeSmithxyz/dwmblocks#72]
The status bar is great but I think the icons could be made more attractive if siji icons were used. Please consider it https://github.com/stark/siji I have been using Larbs for more than a year and I'm really thankful to you.

**Comment by LukeSmithxyz** [comment]
For the record, I don't like including unnecessary dependencies, especially AUR dependencies in public stuff because it increases the liability for breakage beyond my control. This is why I use gaudy emoji by default.

As it is, people can add fonts like this at their own leisure.
