### ISSUE TITLE
dwmblocks and systray 

### ISSUE THREAD

**Issue by d7eeem** [LukeSmithxyz/dwmblocks#74]
So i was looking at the systray patch and i saw it inverter with dwmblocks patch in dwm.c so my question is if i have dwmblocks i can't have a systray?

**Comment by d7eeem** [comment]
NV i patched it

**Comment by sp4ke** [comment]
@d7eeem I'm also trying to patch systray to dwm, got it working with the LukeSmith's build of dwm however dwmblocks stopped correctly responding to the clicks, when I click the wrong blocks are signaled. 

Do you care to share your patch ? 
I'm struggling to patch the fucntion buttonpress() and I don't have much time to dig in the code
