### ISSUE TITLE
dwmblocks not working with dwm-6.2 vanilla patched with statuscmd 

### ISSUE THREAD

**Issue by Virgilio-AI** [LukeSmithxyz/dwmblocks#78]
so I git clone and installed all dwmblocks,dmenu. but dwm blocks just does not work with my dwm 
even thoug I have it vanilla and installed the statuscmd maybe I am doing something wrong. 
when I just git clone install luke's version of dwm it works perfectly fine but with my dwm it only shows color emojis and updates but it is not clickable at all

**Comment by Virgilio-AI** [comment]
btw this is the rejected file when I patch it
`--- dwm.c
+++ dwm.c
@@ -446,9 +452,23 @@ buttonpress(XEvent *e)
 			arg.ui = 1 << i;
 		} else if (ev->x < x + blw)
 			click = ClkLtSymbol;
-		else if (ev->x > selmon->ww - (int)TEXTW(stext))
+		else if (ev->x > selmon->ww - statusw) {
+			x = selmon->ww - statusw;
 			click = ClkStatusText;
-		else
+			statussig = 0;
+			for (text = s = stext; *s && x <= ev->x; s++) {
+				if ((unsigned char)(*s) < ' ') {
+					ch = *s;
+					*s = '\0';
+					x += TEXTW(text) - lrpad;
+					*s = ch;
+					text = s + 1;
+					if (x >= ev->x)
+						break;
+					statussig = ch;
+				}
+			}
+		} else
 			click = ClkWinTitle;
 	} else if ((c = wintoclient(ev->window))) {
 		focus(c);
@@ -710,9 +730,24 @@ drawbar(Monitor *m)
 
 	/* draw status first so it can be overdrawn by tags later */
 	if (m == selmon) { /* status is only drawn on selected monitor */
+		char *text, *s, ch;
 		drw_setscheme(drw, scheme[SchemeNorm]);
-		tw = TEXTW(stext) - lrpad + 2; /* 2px right padding */
-		drw_text(drw, m->ww - tw, 0, tw, bh, 0, stext, 0);
+
+		x = 0;
+		for (text = s = stext; *s; s++) {
+			if ((unsigned char)(*s) < ' ') {
+				ch = *s;
+				*s = '\0';
+				tw = TEXTW(text) - lrpad;
+				drw_text(drw, m->ww - statusw + x, 0, tw, bh, 0, text, 0);
+				x += tw;
+				*s = ch;
+				text = s + 1;
+			}
+		}
+		tw = TEXTW(text) - lrpad + 2;
+		drw_text(drw, m->ww - statusw + x, 0, tw, bh, 0, text, 0);
+		tw = statusw;
 	}
 
 	for (c = m->clients; c; c = c->next) {
`

**Comment by ftreinat** [comment]
Maybe this is also related to #77?

But anyways, I am currently using upstream dwm with the statussignalcmd patch applied and Luke's dwmblocks version myself and ran into the same problem. I fixed the problem by just modifying two lines in the function *sigstatusbar*.

```
---
 dwm.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/dwm.c b/dwm.c
index 7219cc2..0c5d91f 100644
--- a/dwm.c
+++ b/dwm.c
@@ -1704,11 +1704,11 @@ sigstatusbar(const Arg *arg)

        if (!statussig)
                return;
-       sv.sival_int = arg->i;
+       sv.sival_int = arg->i | (statussig << 8);
        if ((statuspid = getstatusbarpid()) <= 0)
                return;

-       sigqueue(statuspid, SIGRTMIN+statussig, sv);
+       sigqueue(statuspid, SIGUSR1, sv);
 }

 void
--
```

**Comment by Virgilio-AI** [comment]
@ftreinat oh that totally solved the problem also, and yes it was actually related to the #77 . thank's for replying tho. I guess I will close this now
