### ISSUE TITLE
Why do i have unwanted boxed characters here

### ISSUE THREAD

**Issue by rachitm99** [LukeSmithxyz/dwmblocks#79]
![screen](https://user-images.githubusercontent.com/65394139/125078657-577c6b80-e0e0-11eb-9606-050ec7974d21.png)

**Comment by rachitm99** [comment]
my dwm fonts are jetbrains mono and joypixels and when i removed jetbrains and made joy pixles the default the boxex did disapear but the joy pixel font did look ugly so is it a font problem ?  i have even tried monospace and anonymous pro fonts but the boxex remained the same

**Comment by norinorin** [comment]
I believe those are signal characters. Try applying this patch https://github.com/LukeSmithxyz/dwm/commit/0c7644eebcceb30621091b2edce798a204f8bdbc. Or take a look at the `copyvalidchars()` function which removes all the signal characters.

**Comment by ganeshhindinamani** [comment]
To resolve this issue, you need to patch the dwm with statuscmd 6.2 patch.
