### ISSUE TITLE
dwmblock not printing properly

### ISSUE THREAD

**Issue by Abh15h3k** [LukeSmithxyz/dwmblocks#8]
After a `yay` update dwmblocks is printing some box symbols.

![image](https://user-images.githubusercontent.com/40197742/79827953-494c0d80-83bd-11ea-9d8d-e2bf05f4e96f.png)

theres no box symbols when simply executing the command in terminal. and changing/removing he delim doesnt get rid of the the box symbols

![image](https://user-images.githubusercontent.com/40197742/79828065-8fa16c80-83bd-11ea-923e-fa936f3fa755.png)

**Comment by kronikpillow** [comment]
yay update dwmblocks? since when is dwmblocks installed by yay?

**Comment by kronikpillow** [comment]
I don't have such issues on his dwmblocks ... did you update to his latest dwmbuild? that's probably because of the clickable dwmblocks update

**Comment by Abh15h3k** [comment]
never said `yay` updated dwmblocks. what i said was after a `yay` update. "pause". dwmblocks started printing those box symbols.

**Comment by Abh15h3k** [comment]
> I don't have such issues on his dwmblocks ... did you update to his latest dwmbuild? that's probably because of the clickable dwmblocks update

yeah. i have to try that. i just noticed his update

**Comment by LukeSmithxyz** [comment]
You need the latest dwm build as well if you don't have it.

**Comment by charlie39** [comment]
That looks man. Take it as a new feature

**Comment by Abh15h3k** [comment]
> You need the latest dwm build as well if you don't have it.

yup. working fine after latest build of dwm
