### ISSUE TITLE
Errors while running dwmblocks

### ISSUE THREAD

**Issue by Pranjalmet** [LukeSmithxyz/dwmblocks#83]
/usr/local/bin/statusbar/sb-tasks: line 9: tsp: command not found
/usr/local/bin/statusbar/sb-music: line 18: mpc: command not found
/usr/local/bin/statusbar/sb-music: line 3: mpc: command not found
/usr/local/bin/statusbar/sb-volume: line 16: pamixer: command not found
/usr/local/bin/statusbar/sb-volume: line 16: [: =: unary operator expected
/usr/local/bin/statusbar/sb-volume: line 18: pamixer: command not found
/usr/local/bin/statusbar/sb-volume: line 20: [: : integer expression expected
/usr/local/bin/statusbar/sb-volume: line 22: [: : integer expression expected
/usr/local/bin/statusbar/sb-tasks: line 9: tsp: command not found
/usr/local/bin/statusbar/sb-tasks: line 9: tsp: command not found
/usr/local/bin/statusbar/sb-tasks: line 9: tsp: command not found

copied everything as in github and didn't made any changes

**Comment by markring40-git** [comment]
What OS are you running?  Do you have task spooler, pamixer and mpc installed? Are your sb scripts executable?  have your tried rerunning sh larbs.sh?

**Comment by Pranjalmet** [comment]
thanks it helped, pamixer wasn't installed (Dumb me)
