### ISSUE TITLE
Time and volume is not updating 

### ISSUE THREAD

**Issue by Pranjalmet** [LukeSmithxyz/dwmblocks#85]
time is not updating after 15-30 minutes (i didn't have a count of it) and volume is not updating after i change it using keyboard bindings 

Config files for Dwmblocks:
[/dwmblocks/config.h](https://github.com/Pranjalmet/Arch/blob/ed848fae5c725af48d131049d0387102a80904c4/dwmblocks/config.h)
....
[/dwmblocks/dwmblocks.c](https://github.com/Pranjalmet/Arch/blob/ed848fae5c725af48d131049d0387102a80904c4/dwmblocks/dwmblocks.c)
......

Config files for sb-clock and sb-volume
[sb-clock](https://github.com/Pranjalmet/Arch/blob/ed848fae5c725af48d131049d0387102a80904c4/statusbar/sb-clock)
.......
[sb-volume](https://github.com/Pranjalmet/Arch/blob/ed848fae5c725af48d131049d0387102a80904c4/statusbar/sb-volume)

And maybe my whole dwmblock is not updating that much frequently i use volume and time very often and those are which i can see not updating

**Comment by LukeSmithxyz** [comment]
If nothing is updating, you've probably killed dwmblocks with an error, possibly by sending it a bad kill signal. Kill it and run it from the command line and see if you get any errors.

**Comment by Pranjalmet** [comment]
running it on terminal gives no error it just updates for the time i run it and then back to not updating it anymore

**Comment by LukeSmithxyz** [comment]
But is the process active when not updating?

Show me the kill signals you're using.

**Comment by Pranjalmet** [comment]
i killed it using htop and after running it using "dwmblocks &" it shows me no errors other than "[1] 1221"

**Comment by LukeSmithxyz** [comment]
Okay, but what are the kill signals you are using to update the modules?

**Comment by Pranjalmet** [comment]
Maybe I'm not familiar with kill signals, would you please tell me how to do use them

**Comment by LukeSmithxyz** [comment]
Read the readme.
