### ISSUE TITLE
sb-pacpackages

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/dwmblocks#88]
seems like `sb-mailbox` and `sb-pacpackages` are not working, if i run `sb-popupgrade` works fine. I am on Artix with a clean install of LARBS.

**Comment by markring40-git** [comment]
Do you have the checkup cron job running?  Do you have neomutt setup?

**Comment by focus85** [comment]
> Do you have the checkup cron job running?  Do you have neomutt setup?

Yes, cronjob is running as a root and I have neomutt setup
