### ISSUE TITLE
empty pipes in dwmblocks

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/dwmblocks#9]
there are empty pipes in dwmblocks, this wasn't the case until you removed the option to set icons I guess .. as it started happening after 

![pic-selected-200421-1220-10](https://user-images.githubusercontent.com/48420193/79855574-70114080-83cb-11ea-8795-2926fee1f7ef.png)

**Comment by LukeSmithxyz** [comment]
I don't think it's specifically that change, but the clickable statusbar patch. It has to print some kind of characters to work. Not sure what to do about this yet.

**Comment by kronikpillow** [comment]
for the first few days of that patch, it wasn't showing up ... and suddenly it started .. but okay, I leave it to you, I'm no coding expert :)

**Comment by LukeSmithxyz** [comment]
I'm looking at it now and yeah actually it looks like a little conflict between the two. I'll either fix it or just renable the icon feature.
